using System.Collections.Generic;
using System.Linq;

public partial class GeospatialManager
{
    void ClusterAndBuildList(List<KakaoDocument> allPlaces)
    {
        _autoGeneratedBuildingList.Clear();
        List<List<KakaoDocument>> addressGroups = allPlaces
            .Where(document => document != null)
            .GroupBy(document => NormalizeText(GetBestAddress(document)))
            .Select(group => group.ToList())
            .ToList();

        foreach (List<KakaoDocument> addressGroup in addressGroups)
        {
            if (ShouldUseRepresentativeInstitutionalClustering(addressGroup))
            {
                foreach (List<KakaoDocument> cluster in BuildInstitutionalRepresentativeClusters(addressGroup))
                {
                    if (cluster.Count > 0)
                    {
                        _autoGeneratedBuildingList.Add(ProcessClusterIntoBuildingData(cluster));
                    }
                }
                continue;
            }

            foreach (List<KakaoDocument> cluster in BuildDistanceAddressClusters(addressGroup))
            {
                if (cluster.Count > 0)
                {
                    _autoGeneratedBuildingList.Add(ProcessClusterIntoBuildingData(cluster));
                }
            }
        }
    }

    List<List<KakaoDocument>> BuildDistanceAddressClusters(List<KakaoDocument> documents)
    {
        List<List<KakaoDocument>> clusters = new List<List<KakaoDocument>>();
        HashSet<int> processedIndices = new HashSet<int>();

        for (int i = 0; i < documents.Count; i++)
        {
            if (processedIndices.Contains(i)) continue;

            List<KakaoDocument> newCluster = new List<KakaoDocument>();
            KakaoDocument baseDoc = documents[i];
            newCluster.Add(baseDoc);
            processedIndices.Add(i);

            for (int j = i + 1; j < documents.Count; j++)
            {
                if (processedIndices.Contains(j)) continue;

                KakaoDocument compareDoc = documents[j];
                double distance = HaversineDistance(
                    double.Parse(baseDoc.y),
                    double.Parse(baseDoc.x),
                    double.Parse(compareDoc.y),
                    double.Parse(compareDoc.x));

                if (distance <= clusterRadius)
                {
                    newCluster.Add(compareDoc);
                    processedIndices.Add(j);
                }
            }

            clusters.Add(newCluster);
        }

        return clusters;
    }

    bool ShouldUseRepresentativeInstitutionalClustering(List<KakaoDocument> addressGroup)
    {
        return addressGroup != null &&
               addressGroup.Count > 0 &&
               addressGroup.Any(IsRepresentativeBuildingCandidate);
    }

    List<List<KakaoDocument>> BuildInstitutionalRepresentativeClusters(List<KakaoDocument> addressGroup)
    {
        List<List<KakaoDocument>> clusters = new List<List<KakaoDocument>>();
        Dictionary<string, List<KakaoDocument>> clustersByToken = new Dictionary<string, List<KakaoDocument>>();

        foreach (KakaoDocument representative in SelectRepresentativeBuildingDocuments(addressGroup))
        {
            string tokenKey = NormalizeText(GetInstitutionalBuildingToken(representative));
            if (string.IsNullOrWhiteSpace(tokenKey) || clustersByToken.ContainsKey(tokenKey))
            {
                continue;
            }

            List<KakaoDocument> cluster = new List<KakaoDocument> { representative };
            clustersByToken[tokenKey] = cluster;
            clusters.Add(cluster);
        }

        List<KakaoDocument> leftovers = new List<KakaoDocument>();

        foreach (KakaoDocument document in addressGroup)
        {
            if (document == null)
            {
                continue;
            }

            string tokenKey = NormalizeText(GetInstitutionalBuildingToken(document));
            if (!string.IsNullOrWhiteSpace(tokenKey) &&
                clustersByToken.TryGetValue(tokenKey, out List<KakaoDocument> exactMatchCluster))
            {
                if (!exactMatchCluster.Contains(document))
                {
                    exactMatchCluster.Add(document);
                }
                continue;
            }

            if (TryAssignDocumentToNearestRepresentativeCluster(document, clustersByToken, out List<KakaoDocument> nearestCluster))
            {
                if (!nearestCluster.Contains(document))
                {
                    nearestCluster.Add(document);
                }
                continue;
            }

            leftovers.Add(document);
        }

        if (leftovers.Count > 0)
        {
            foreach (List<KakaoDocument> fallbackCluster in BuildDistanceAddressClusters(leftovers))
            {
                if (fallbackCluster.Count > 0)
                {
                    clusters.Add(fallbackCluster);
                }
            }
        }

        return clusters;
    }

    bool TryAssignDocumentToNearestRepresentativeCluster(
        KakaoDocument document,
        Dictionary<string, List<KakaoDocument>> clustersByToken,
        out List<KakaoDocument> matchedCluster)
    {
        matchedCluster = null;
        if (document == null || clustersByToken == null || clustersByToken.Count == 0)
        {
            return false;
        }

        string explicitToken = NormalizeText(GetInstitutionalBuildingToken(document));
        if (!string.IsNullOrWhiteSpace(explicitToken) && !clustersByToken.ContainsKey(explicitToken))
        {
            return false;
        }

        float bestDistance = float.MaxValue;

        foreach (KeyValuePair<string, List<KakaoDocument>> pair in clustersByToken)
        {
            KakaoDocument representative = pair.Value
                .OrderByDescending(GetRepresentativeBuildingCandidateScore)
                .ThenByDescending(GetDocumentQualityScore)
                .FirstOrDefault();
            if (representative == null)
            {
                continue;
            }

            float distance = (float)HaversineDistance(
                double.Parse(document.y), double.Parse(document.x),
                double.Parse(representative.y), double.Parse(representative.x));

            if (distance > institutionalFacilityAssignmentRadius)
            {
                continue;
            }

            if (distance < bestDistance)
            {
                bestDistance = distance;
                matchedCluster = pair.Value;
            }
        }

        return matchedCluster != null;
    }
}
