using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;


//현재 위치를 받아서 여러 Kakao 검색을 돌리고, 결과를 병합하고, 클러스터링하고, 최종 건물 리스트를 만든 뒤 앵커 생성 단계로 넘기는 파일
public partial class GeospatialManager
{
    private class SearchDiagnostics
    {
        public int commercialRequestCount;
        public int campusRequestCount;
        public int keywordRequestCount;
        public int commercialResultCount;
        public int campusResultCount;
        public int keywordResultCount;
        public int mergedUniqueCount;
    }

    IEnumerator FetchAndClusterNearbyPlaces(double lat, double lon)
    {
        ResetAnchorDebugOverlay();
        arUIManager?.SetTrackingStabilizingMode();
        Dictionary<string, KakaoDocument> mergedPlaces = new Dictionary<string, KakaoDocument>();
        SearchDiagnostics diagnostics = new SearchDiagnostics();
        int successCount = 0;

        if (useCommercialCategorySearch)
        {
            foreach (string categoryCode in GetCommercialCategoryCodes())
            {
                bool categorySucceeded = false;
                diagnostics.commercialRequestCount++;
                yield return StartCoroutine(FetchNearbyPlacesFromKakaoCategory(lat, lon, categoryCode, "commercial", 100, (requestSucceeded, fetchedDocuments) =>
                {
                    categorySucceeded = requestSucceeded;
                    diagnostics.commercialResultCount += fetchedDocuments.Count;
                    MergeFetchedPlaces(mergedPlaces, fetchedDocuments);
                }));

                if (categorySucceeded)
                {
                    successCount++;
                }
            }
        }

        // 현재는 일반 건물만 사용하므로 campus 카테고리 검색은 비활성화한다.
        // if (useCampusCategorySearch)
        // {
        //     foreach (string categoryCode in GetCampusCategoryCodes())
        //     {
        //         bool categorySucceeded = false;
        //         diagnostics.campusRequestCount++;
        //         yield return StartCoroutine(FetchNearbyPlacesFromKakaoCategory(lat, lon, categoryCode, "campus", 200, (requestSucceeded, fetchedDocuments) =>
        //         {
        //             categorySucceeded = requestSucceeded;
        //             diagnostics.campusResultCount += fetchedDocuments.Count;
        //             MergeFetchedPlaces(mergedPlaces, fetchedDocuments);
        //         }));
        //
        //         if (categorySucceeded)
        //         {
        //             successCount++;
        //         }
        //     }
        // }

        if (useKeywordSearch)
        {
            foreach (string keywordQuery in GetKeywordQueries())
            {
                bool keywordSucceeded = false;
                diagnostics.keywordRequestCount++;
                yield return StartCoroutine(FetchNearbyPlacesFromKakaoKeyword(lat, lon, keywordQuery, 300, (requestSucceeded, fetchedDocuments) =>
                {
                    keywordSucceeded = requestSucceeded;
                    diagnostics.keywordResultCount += fetchedDocuments.Count;
                    MergeFetchedPlaces(mergedPlaces, fetchedDocuments);
                }));

                if (keywordSucceeded)
                {
                    successCount++;
                }
            }
        }

        if (successCount == 0)
        {
            Debug.LogError("All Kakao place requests failed.");
            arUIManager?.ShowToast("주변 장소를 불러오지 못했습니다.");
            ClearAllContent();
            yield break;
        }

        List<KakaoDocument> allFetchedPlaces = mergedPlaces.Values.ToList();
        diagnostics.mergedUniqueCount = allFetchedPlaces.Count;
        LogSearchDiagnostics(diagnostics, allFetchedPlaces);
        ClusterAndBuildList(allFetchedPlaces);
        arUIManager?.SetBuildingCountStatus(_autoGeneratedBuildingList.Count);

        if (_autoGeneratedBuildingList.Count == 0)
        {
            Debug.LogWarning("No nearby places were found for the current location.");
            arUIManager?.ShowToast("주변 장소 정보가 없습니다.");
        }

        yield return StartCoroutine(CreateAllBuildingAnchors());
    }

    void LogSearchDiagnostics(SearchDiagnostics diagnostics, List<KakaoDocument> mergedPlaces)
    {
        if (!logSearchDiagnostics)
        {
            return;
        }

        int injeHits = mergedPlaces.Count(doc => !string.IsNullOrWhiteSpace(doc.place_name) && doc.place_name.Contains("인제대"));
        int dormitoryHits = mergedPlaces.Count(doc => !string.IsNullOrWhiteSpace(doc.place_name) && (doc.place_name.Contains("기숙사") || doc.place_name.Contains("원룸")));
        int nightlifeHits = mergedPlaces.Count(doc => !string.IsNullOrWhiteSpace(doc.place_name) && (doc.place_name.Contains("술") || doc.place_name.Contains("주점") || doc.place_name.Contains("포차")));

        Debug.Log(
            $"[SearchDiagnostics] commercial requests/results: {diagnostics.commercialRequestCount}/{diagnostics.commercialResultCount}, " +
            $"campus requests/results: {diagnostics.campusRequestCount}/{diagnostics.campusResultCount}, " +
            $"keyword requests/results: {diagnostics.keywordRequestCount}/{diagnostics.keywordResultCount}, " +
            $"merged unique: {diagnostics.mergedUniqueCount}, " +
            $"inje hits: {injeHits}, dormitory or room hits: {dormitoryHits}, nightlife hits: {nightlifeHits}");
    }
}
