using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Google.XR.ARCoreExtensions;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;
using UnityEngine.Networking;
using System.Linq;
using System;
using System.IO;

public class GeospatialManager : MonoBehaviour
{
    [Serializable]
    private class LocalApiKeys
    {
        public string kakaoRestApiKey;
        public string androidCloudServicesApiKey;
        public string iosCloudServicesApiKey;
    }

    // --- Inspector Settings ---
    [Header("AR Components")]
    public AREarthManager EarthManager; // 위도 경도
    public ARAnchorManager AnchorManager; // 앵커 관리

    [Header("UI Manager Connection")]
    public ARUIManager arUIManager; // UI 매니저 연결

    [Header("API & Data")]
    public string kakaoRestApiKey; // 카카오 REST API 호출 키
    public int searchRadius = 200; // 검색 반경 (미터 단위)
    public float clusterRadius = 20.0f; // 클러스터링 반경 (미터 단위)
    public List<string> categoryCodes = new List<string> { "MT1", "CS2", "CE7", "HP8", "PM9", "FD6", "SC4" };
    // 특정 카테고리만 검색해서 건물 정보를 구성

    [Header("Marker Settings")]
    public GameObject buildingMarkerPrefab;  // 건물 마커 프리팹
    private BuildingMarker _currentActiveMarker; // 현재 선택된 마커 참조

    [Header("Geospatial Content")]
    private List<BuildingData> _autoGeneratedBuildingList = new List<BuildingData>();
    // 건물 인식 및 정보 표시 설정
    public float detectionRadius = 100.0f; // 감지 반경 (미터 단위)
    public float detectionAngle = 60.0f;   // 감지 각도 (도 단위)
    public float verticalAngleLimit = 60.0f;// 수직 각도 제한 (도 단위)
    public float refreshDistance = 100.0f; // 위치 변경에 따른 데이터 새로고침 기준 (미터 단위)

    // --- Internal Variables ---
    private Transform _cameraTransform; // 카메라 트랜스폼 참조
    private BuildingData _currentDetectedBuilding; // 현재 감지된 건물 정보
    private BuildingData _selectedBuilding;// 사용자가 선택한 건물 정보  
    private Dictionary<string, ARGeospatialAnchor> _buildingAnchors = new Dictionary<string, ARGeospatialAnchor>();
    // 위치 기반 데이터 관리(건물 이름을 키로 앵커 참조 저장)
    private LocationInfo _lastLoadedLocation;
    private bool _isDataLoaded = false;
    private bool _isViewingInfo = false;

    IEnumerator Start()
    {
        TryLoadKakaoApiKeyFromLocalFile();
        _cameraTransform = Camera.main.transform; // 메인 카메라 트랜스폼 참조

        if (arUIManager != null)
        {
            arUIManager.OnClickAction += HandleActionButtonClick; // 액션 버튼 클릭 시 처리

            arUIManager.OnClickDetail += () => // 상세보기 버튼 클릭 시 처리
            {
                if (_selectedBuilding != null)
                {
                    arUIManager.OpenDetailView(_selectedBuilding);
                }
            };
        }
        else
        {
            Debug.LogError("ARUIManager Connection Failed");
        }

        if (!Input.location.isEnabledByUser)
        {
            Debug.Log("Location Permission Denied");
            yield break;
        }

        Input.location.Start();
        int maxWait = 20;
        while (Input.location.status == LocationServiceStatus.Initializing && maxWait > 0)
        {
            yield return new WaitForSeconds(1);
            maxWait--;
        }

        if (Input.location.status == LocationServiceStatus.Failed || Input.location.status != LocationServiceStatus.Running)
        {
            Debug.Log("Location Service Failed");
            yield break;
        }

        yield return StartCoroutine(ReloadDataAtCurrentLocation());

        while (EarthManager.EarthTrackingState != TrackingState.Tracking)
        {
            yield return new WaitForSeconds(1.0f);
        }
    }

    void TryLoadKakaoApiKeyFromLocalFile()
    {
        if (!string.IsNullOrWhiteSpace(kakaoRestApiKey)) return;

        string filePath = Path.Combine(Application.streamingAssetsPath, "LocalApiKeys.json");
        if (!File.Exists(filePath))
        {
            Debug.LogWarning($"Local API key file not found: {filePath}");
            return;
        }

        try
        {
            string json = File.ReadAllText(filePath);
            LocalApiKeys keys = JsonUtility.FromJson<LocalApiKeys>(json);
            if (!string.IsNullOrWhiteSpace(keys?.kakaoRestApiKey))
            {
                kakaoRestApiKey = keys.kakaoRestApiKey;
            }
        }
        catch (Exception ex)
        {
            Debug.LogError($"Failed to load local API keys: {ex.Message}");
        }
    }

    void Update()
    {
        CheckMovementAndReload(); // 위치 변경에 따른 데이터 새로고침 여부 판단
        if (EarthManager.EarthTrackingState != TrackingState.Tracking) return;
        if (_isViewingInfo) return;
        CheckBuildingDetection(); // 건물 감지 로직 실행
    }

    // --- Building Detection Logic ---
    void CheckBuildingDetection() // 카메라 시점과 위치를 기반으로 가장 적합한 건물 감지 및 UI 업데이트
    {
        BuildingData bestTarget = FindBestTargetFromExistingAnchors();

        if (bestTarget != null)
        {
            if (_currentDetectedBuilding != bestTarget)
            {
                _currentDetectedBuilding = bestTarget;
                arUIManager.SetDetectedMode();
                UpdateMarkerScale(bestTarget.buildingName);
            }
        }
        else
        {
            if (_currentDetectedBuilding != null)
            {
                _currentDetectedBuilding = null;
                arUIManager.SetScanningMode();
                ResetAllMarkers();
            }
        }
    }

    void UpdateMarkerScale(string targetBuildingName)
    {
        if (_currentActiveMarker != null)
        {
            _currentActiveMarker.SetSelected(false);
            _currentActiveMarker = null;
        }

        if (_buildingAnchors.ContainsKey(targetBuildingName))
        {
            ARGeospatialAnchor anchor = _buildingAnchors[targetBuildingName];
            BuildingMarker marker = anchor.GetComponentInChildren<BuildingMarker>();

            if (marker != null)
            {
                marker.SetSelected(true);
                _currentActiveMarker = marker;
            }
        }
    }

    void ResetAllMarkers()
    {
        if (_currentActiveMarker != null)
        {
            _currentActiveMarker.SetSelected(false);
            _currentActiveMarker = null;
        }
    }

    void HandleActionButtonClick()
    {
        if (_isViewingInfo) // 이미 정보 화면을 보고 있다면, 액션 버튼 클릭 시 정보 화면 닫기
        {
            _isViewingInfo = false;
            _selectedBuilding = null;
            arUIManager.SetScanningMode();
            return;
        }

        if (_currentDetectedBuilding != null)
        {
            _isViewingInfo = true;
            _selectedBuilding = _currentDetectedBuilding;
            arUIManager.ShowQuickInfo(_selectedBuilding);
        }
    }

    // --- API & Data Processing ---
    IEnumerator FetchAndClusterNearbyPlaces(double lat, double lon)
    {
        List<KakaoDocument> allFetchedPlaces = new List<KakaoDocument>();
        foreach (string category in categoryCodes)
        {
            yield return StartCoroutine(FetchNearbyPlacesFromKakao(lat, lon, category, allFetchedPlaces));
        }
        ClusterAndBuildList(allFetchedPlaces);
        CreateAllBuildingAnchors();
    }

    IEnumerator FetchNearbyPlacesFromKakao(double lat, double lon, string categoryCode, List<KakaoDocument> targetList)
    {
        for (int page = 1; page <= 3; page++)
        {
            string url = $"https://dapi.kakao.com/v2/local/search/category.json?category_group_code={categoryCode}&x={lon}&y={lat}&radius={searchRadius}&page={page}";
            using (UnityWebRequest webRequest = UnityWebRequest.Get(url))
            {
                webRequest.SetRequestHeader("Authorization", "KakaoAK " + kakaoRestApiKey);
                yield return webRequest.SendWebRequest();

                if (webRequest.result == UnityWebRequest.Result.Success)
                {
                    KakaoResponse response = JsonUtility.FromJson<KakaoResponse>(webRequest.downloadHandler.text);
                    if (response.documents.Length == 0) break;
                    foreach (var doc in response.documents)
                    {
                        if (!targetList.Any(p => p.place_name == doc.place_name)) targetList.Add(doc);
                    }
                    if (response.meta.is_end) break;
                }
                else break;
            }
        }
    }

    // Clustering Logic (Distance + Address Match)
    void ClusterAndBuildList(List<KakaoDocument> allPlaces)
    {
        _autoGeneratedBuildingList.Clear();
        HashSet<int> processedIndices = new HashSet<int>();

        for (int i = 0; i < allPlaces.Count; i++)
        {
            if (processedIndices.Contains(i)) continue;

            List<KakaoDocument> newCluster = new List<KakaoDocument>();
            KakaoDocument baseDoc = allPlaces[i];
            newCluster.Add(baseDoc);
            processedIndices.Add(i);

            for (int j = i + 1; j < allPlaces.Count; j++)
            {
                if (processedIndices.Contains(j)) continue;

                KakaoDocument compareDoc = allPlaces[j];

                double distance = HaversineDistance(double.Parse(baseDoc.y), double.Parse(baseDoc.x),
                    double.Parse(compareDoc.y), double.Parse(compareDoc.x));

                bool isSameAddress = false;
                if (!string.IsNullOrEmpty(baseDoc.road_address_name) && !string.IsNullOrEmpty(compareDoc.road_address_name))
                {
                    string addr1 = baseDoc.road_address_name.Replace(" ", "");
                    string addr2 = compareDoc.road_address_name.Replace(" ", "");
                    isSameAddress = addr1 == addr2;
                }
                else
                {
                    string addr1 = baseDoc.address_name.Replace(" ", "");
                    string addr2 = compareDoc.address_name.Replace(" ", "");
                    isSameAddress = addr1 == addr2;
                }

                if (distance <= clusterRadius && isSameAddress)
                {
                    newCluster.Add(compareDoc);
                    processedIndices.Add(j);
                }
            }
            _autoGeneratedBuildingList.Add(ProcessClusterIntoBuildingData(newCluster));
        }
    }

    // Convert API Data to BuildingData
    BuildingData ProcessClusterIntoBuildingData(List<KakaoDocument> cluster)
    {
        BuildingData newBuilding = new BuildingData();
        KakaoDocument representative = cluster[0];

        newBuilding.buildingName = representative.place_name;
        newBuilding.latitude = double.Parse(representative.y);
        newBuilding.longitude = double.Parse(representative.x);
        newBuilding.altitude = 0;
        newBuilding.fetchedAddress = representative.road_address_name;
        newBuilding.description = representative.category_group_name;

        newBuilding.phoneNumber = representative.phone;
        newBuilding.placeUrl = representative.place_url;
        newBuilding.zipCode = representative.address_name;

        newBuilding.facilities = new List<FacilityInfo>();
        foreach (var doc in cluster)
        {
            FacilityInfo info = new FacilityInfo();
            info.name = doc.place_name;
            info.phone = doc.phone;
            info.category = doc.category_group_name;
            info.placeUrl = doc.place_url;

            newBuilding.facilities.Add(info);
        }

        return newBuilding;
    }

    void CreateAllBuildingAnchors()
    {
        foreach (var anchor in _buildingAnchors.Values) if (anchor != null) Destroy(anchor.gameObject);
        _buildingAnchors.Clear();

        foreach (var building in _autoGeneratedBuildingList)
        {
            ARGeospatialAnchor anchor = AnchorManager.AddAnchor(building.latitude, building.longitude, building.altitude, Quaternion.identity);

            if (anchor != null)
            {
                _buildingAnchors.Add(building.buildingName, anchor);

                if (buildingMarkerPrefab != null)
                {
                    GameObject markerObj = Instantiate(buildingMarkerPrefab, anchor.transform);
                    markerObj.transform.localPosition = Vector3.zero;
                }
            }
        }
    }
    //건물 인식 방식 결정
    BuildingData FindBestTargetFromExistingAnchors() // 카메라 시점과 위치를 기반으로 가장 적합한 건물 감지
    {
        float pitchAngle = 90.0f - Vector3.Angle(_cameraTransform.forward, Vector3.up);
        if (Mathf.Abs(pitchAngle) > verticalAngleLimit) return null;

        BuildingData bestTarget = null;

        float minDistance = float.MaxValue;

        foreach (var building in _autoGeneratedBuildingList)
        {
            if (_buildingAnchors.ContainsKey(building.buildingName))
            {
                ARGeospatialAnchor anchor = _buildingAnchors[building.buildingName];
                if (anchor == null) continue;

                Vector3 buildingWorldPosition = anchor.transform.position;
                float distance = Vector3.Distance(_cameraTransform.position, buildingWorldPosition);

                if (distance > detectionRadius) continue;

                Vector3 cameraForward = _cameraTransform.forward;
                cameraForward.y = 0;
                Vector3 directionToBuilding = buildingWorldPosition - _cameraTransform.position;
                directionToBuilding.y = 0;

                float angle = Vector3.Angle(cameraForward.normalized, directionToBuilding.normalized);

                if (angle < detectionAngle / 2)
                {
                    if (distance < minDistance)
                    {
                        minDistance = distance;
                        bestTarget = building;
                    }
                }
            }
        }
        return bestTarget;
    }
    void CheckMovementAndReload() // 위치 변경에 따른 데이터 새로고침 여부 판단
    {
        if (Input.location.status == LocationServiceStatus.Running && _isDataLoaded)
        {
            LocationInfo currentLoc = Input.location.lastData;
            double distance = HaversineDistance(_lastLoadedLocation.latitude, _lastLoadedLocation.longitude, currentLoc.latitude, currentLoc.longitude);
            if (distance >= refreshDistance) { StartCoroutine(ReloadDataAtCurrentLocation()); }
        }
    }
    IEnumerator ReloadDataAtCurrentLocation() // 현재 위치에서 데이터 새로고침
    {
        LocationInfo currentLoc = Input.location.lastData;
        _isDataLoaded = false;
        yield return StartCoroutine(FetchAndClusterNearbyPlaces(currentLoc.latitude, currentLoc.longitude));
        _lastLoadedLocation = currentLoc;
        _isDataLoaded = true;
    }
    private double HaversineDistance(double lat1, double lon1, double lat2, double lon2)
    // 두 지점 간의 거리를 계산하는 Haversine 공식
    {
        const double R = 6371e3; var phi1 = lat1 * (Math.PI / 180.0);
        var phi2 = lat2 * (Math.PI / 180.0); var deltaPhi = (lat2 - lat1) * (Math.PI / 180.0);
        var deltaLambda = (lon2 - lon1) * (Math.PI / 180.0);
        var a = Math.Sin(deltaPhi / 2) * Math.Sin(deltaPhi / 2) + Math.Cos(phi1) * Math.Cos(phi2) * Math.Sin(deltaLambda / 2) * Math.Sin(deltaLambda / 2);
        var c = 2 * Math.Atan2(Math.Sqrt(a), Math.Sqrt(1 - a)); return R * c;
    }
    void ClearAllContent() { foreach (var anchor in _buildingAnchors.Values) if (anchor != null) Destroy(anchor.gameObject); _buildingAnchors.Clear(); _autoGeneratedBuildingList.Clear(); _currentDetectedBuilding = null; }
}

// --- Data Classes ---
[System.Serializable]
public class KakaoResponse
{
    public KakaoDocument[] documents;
    public KakaoMeta meta;
}

[System.Serializable]
public class KakaoDocument
{
    public string place_name;
    public string road_address_name;
    public string address_name;
    public string category_group_name;
    public string phone;
    public string place_url;
    public string y;
    public string x;
}

[System.Serializable]
public class KakaoMeta
{
    public int total_count;
    public bool is_end;
}
