using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class GeospatialManager
{
    void ClusterAndBuildList(List<KakaoDocument> allPlaces)
    {
        _autoGeneratedBuildingList.Clear();
        List<List<KakaoDocument>> addressGroups = allPlaces
            .Where(document => document != null)
            .GroupBy(document => NormalizeText(GetBestAddress(document)))
            .Select(group => group.ToList())
            .ToList();

        foreach (List<KakaoDocument> addressGroup in addressGroups)
        {
            if (ShouldUseRepresentativeInstitutionalClustering(addressGroup))
            {
                foreach (List<KakaoDocument> cluster in BuildInstitutionalRepresentativeClusters(addressGroup))
                {
                    if (cluster.Count > 0)
                    {
                        _autoGeneratedBuildingList.Add(ProcessClusterIntoBuildingData(cluster));
                    }
                }
                continue;
            }

            foreach (List<KakaoDocument> cluster in BuildDistanceAddressClusters(addressGroup))
            {
                if (cluster.Count > 0)
                {
                    _autoGeneratedBuildingList.Add(ProcessClusterIntoBuildingData(cluster));
                }
            }
        }
    }

    List<List<KakaoDocument>> BuildDistanceAddressClusters(List<KakaoDocument> documents)
    {
        List<List<KakaoDocument>> clusters = new List<List<KakaoDocument>>();
        HashSet<int> processedIndices = new HashSet<int>();

        for (int i = 0; i < documents.Count; i++)
        {
            if (processedIndices.Contains(i)) continue;

            List<KakaoDocument> newCluster = new List<KakaoDocument>();
            KakaoDocument baseDoc = documents[i];
            newCluster.Add(baseDoc);
            processedIndices.Add(i);

            for (int j = i + 1; j < documents.Count; j++)
            {
                if (processedIndices.Contains(j)) continue;

                KakaoDocument compareDoc = documents[j];
                double distance = HaversineDistance(
                    double.Parse(baseDoc.y),
                    double.Parse(baseDoc.x),
                    double.Parse(compareDoc.y),
                    double.Parse(compareDoc.x));

                if (distance <= clusterRadius)
                {
                    newCluster.Add(compareDoc);
                    processedIndices.Add(j);
                }
            }

            clusters.Add(newCluster);
        }

        return clusters;
    }

    bool ShouldUseRepresentativeInstitutionalClustering(List<KakaoDocument> addressGroup)
    {
        return addressGroup != null &&
               addressGroup.Count > 0 &&
               addressGroup.Any(IsRepresentativeBuildingCandidate);
    }

    List<List<KakaoDocument>> BuildInstitutionalRepresentativeClusters(List<KakaoDocument> addressGroup)
    {
        List<List<KakaoDocument>> clusters = new List<List<KakaoDocument>>();
        Dictionary<string, List<KakaoDocument>> clustersByToken = new Dictionary<string, List<KakaoDocument>>();

        foreach (KakaoDocument representative in SelectRepresentativeBuildingDocuments(addressGroup))
        {
            string tokenKey = NormalizeText(GetInstitutionalBuildingToken(representative));
            if (string.IsNullOrWhiteSpace(tokenKey) || clustersByToken.ContainsKey(tokenKey))
            {
                continue;
            }

            List<KakaoDocument> cluster = new List<KakaoDocument> { representative };
            clustersByToken[tokenKey] = cluster;
            clusters.Add(cluster);
        }

        List<KakaoDocument> leftovers = new List<KakaoDocument>();

        foreach (KakaoDocument document in addressGroup)
        {
            if (document == null)
            {
                continue;
            }

            string tokenKey = NormalizeText(GetInstitutionalBuildingToken(document));
            if (!string.IsNullOrWhiteSpace(tokenKey) &&
                clustersByToken.TryGetValue(tokenKey, out List<KakaoDocument> exactMatchCluster))
            {
                if (!exactMatchCluster.Contains(document))
                {
                    exactMatchCluster.Add(document);
                }
                continue;
            }

            if (TryAssignDocumentToNearestRepresentativeCluster(document, clustersByToken, out List<KakaoDocument> nearestCluster))
            {
                if (!nearestCluster.Contains(document))
                {
                    nearestCluster.Add(document);
                }
                continue;
            }

            leftovers.Add(document);
        }

        if (leftovers.Count > 0)
        {
            foreach (List<KakaoDocument> fallbackCluster in BuildDistanceAddressClusters(leftovers))
            {
                if (fallbackCluster.Count > 0)
                {
                    clusters.Add(fallbackCluster);
                }
            }
        }

        return clusters;
    }

    bool TryAssignDocumentToNearestRepresentativeCluster(
        KakaoDocument document,
        Dictionary<string, List<KakaoDocument>> clustersByToken,
        out List<KakaoDocument> matchedCluster)
    {
        matchedCluster = null;
        if (document == null || clustersByToken == null || clustersByToken.Count == 0)
        {
            return false;
        }

        string explicitToken = NormalizeText(GetInstitutionalBuildingToken(document));
        if (!string.IsNullOrWhiteSpace(explicitToken) && !clustersByToken.ContainsKey(explicitToken))
        {
            return false;
        }

        float bestDistance = float.MaxValue;

        foreach (KeyValuePair<string, List<KakaoDocument>> pair in clustersByToken)
        {
            KakaoDocument representative = pair.Value
                .OrderByDescending(GetRepresentativeBuildingCandidateScore)
                .ThenByDescending(GetDocumentQualityScore)
                .FirstOrDefault();
            if (representative == null)
            {
                continue;
            }

            float distance = (float)HaversineDistance(
                double.Parse(document.y), double.Parse(document.x),
                double.Parse(representative.y), double.Parse(representative.x));

            if (distance > institutionalFacilityAssignmentRadius)
            {
                continue;
            }

            if (distance < bestDistance)
            {
                bestDistance = distance;
                matchedCluster = pair.Value;
            }
        }

        return matchedCluster != null;
    }

    List<KakaoDocument> SelectRepresentativeBuildingDocuments(List<KakaoDocument> addressGroup)
    {
        Dictionary<KakaoDocument, int> scoreMap = BuildRepresentativeCandidateScoreMap(addressGroup);

        return addressGroup
            .Where(IsRepresentativeBuildingCandidate)
            .GroupBy(GetRepresentativeBuildingClusterKey)
            .Select(group => group
                .OrderByDescending(document => scoreMap.TryGetValue(document, out int score) ? score : int.MinValue)
                .ThenByDescending(GetDocumentQualityScore)
                .ThenByDescending(document => !string.IsNullOrWhiteSpace(document.road_address_name))
                .ThenByDescending(document => document.place_name?.Length ?? 0)
                .First())
            .ToList();
    }

    bool IsRepresentativeBuildingCandidate(KakaoDocument document)
    {
        if (document == null)
        {
            return false;
        }

        if (!LooksLikeAnchorEligibleBuilding(document))
        {
            return false;
        }

        if (GetClusterGroupingType(document) != ClusterGroupingType.Institutional)
        {
            return false;
        }

        return GetRepresentativeBuildingCandidateScore(document) > 0;
    }

    int GetRepresentativeBuildingCandidateScore(KakaoDocument document)
    {
        if (document == null)
        {
            return int.MinValue;
        }

        if (!LooksLikeAnchorEligibleBuilding(document))
        {
            return int.MinValue;
        }

        int score = GetDocumentQualityScore(document);
        string normalizedPlaceName = NormalizeText(document.place_name);
        string normalizedToken = NormalizeText(GetInstitutionalBuildingToken(document));
        string normalizedCategory = NormalizeText(document.category_name);
        bool hasBuildingToken = !string.IsNullOrWhiteSpace(normalizedToken);
        bool looksLikeFacility = LooksLikeInstitutionalFacility(document);
        bool isCommercial = GetClusterGroupingType(document) == ClusterGroupingType.Commercial;

        if (NormalizeText(document.category_group_name) == NormalizeText("키워드 검색"))
        {
            score += 45;
        }

        if (!string.IsNullOrWhiteSpace(normalizedCategory) &&
            (normalizedCategory.Contains(NormalizeText("학교부속시설")) ||
             normalizedCategory.Contains(NormalizeText("대학교")) ||
             normalizedCategory.Contains(NormalizeText("학교")) ||
             normalizedCategory.Contains(NormalizeText("병원"))))
        {
            score += 18;
        }

        if (hasBuildingToken)
        {
            score += 35;
        }

        if (normalizedPlaceName == normalizedToken && !string.IsNullOrWhiteSpace(normalizedToken))
        {
            score += 10;
        }

        if (isCommercial)
        {
            score -= 60;
        }

        if (looksLikeFacility)
        {
            score -= 55;
        }

        return score;
    }

    Dictionary<KakaoDocument, int> BuildRepresentativeCandidateScoreMap(List<KakaoDocument> addressGroup)
    {
        Dictionary<KakaoDocument, int> scoreMap = new Dictionary<KakaoDocument, int>();
        if (addressGroup == null)
        {
            return scoreMap;
        }

        foreach (KakaoDocument document in addressGroup)
        {
            scoreMap[document] = GetRepresentativeBuildingCandidateScore(document) +
                                 GetRepresentativeCentralityScore(document, addressGroup) +
                                 GetRepresentativeTokenSupportScore(document, addressGroup);
        }

        return scoreMap;
    }

    int GetRepresentativeCentralityScore(KakaoDocument document, List<KakaoDocument> addressGroup)
    {
        if (document == null || addressGroup == null || addressGroup.Count <= 1)
        {
            return 0;
        }

        int nearbyCount = 0;
        foreach (KakaoDocument other in addressGroup)
        {
            if (other == null || other == document)
            {
                continue;
            }

            double distance = HaversineDistance(
                double.Parse(document.y), double.Parse(document.x),
                double.Parse(other.y), double.Parse(other.x));

            if (distance <= institutionalFacilityAssignmentRadius)
            {
                nearbyCount++;
            }
        }

        return Mathf.Min(nearbyCount * 8, 32);
    }

    int GetRepresentativeTokenSupportScore(KakaoDocument document, List<KakaoDocument> addressGroup)
    {
        if (document == null || addressGroup == null)
        {
            return 0;
        }

        string clusterKey = NormalizeText(GetRepresentativeBuildingClusterKey(document));
        if (string.IsNullOrWhiteSpace(clusterKey))
        {
            return -20;
        }

        int supportCount = addressGroup.Count(other =>
            other != null &&
            NormalizeText(GetRepresentativeBuildingClusterKey(other)) == clusterKey);

        return Mathf.Min(Mathf.Max(0, supportCount - 1) * 10, 40);
    }

    string GetRepresentativeBuildingClusterKey(KakaoDocument document)
    {
        string buildingToken = NormalizeText(GetInstitutionalBuildingToken(document));
        if (!string.IsNullOrWhiteSpace(buildingToken))
        {
            return buildingToken;
        }

        return NormalizeRepresentativeName(document?.place_name);
    }

    bool LooksLikeInstitutionalFacility(KakaoDocument document)
    {
        string normalizedPlaceName = NormalizeText(document?.place_name);
        string normalizedCategory = NormalizeText(document?.category_name);
        string normalizedGroupCategory = NormalizeText(document?.category_group_name);

        return ContainsAnyKeyword(normalizedPlaceName, InstitutionalFacilityKeywords) ||
               ContainsAnyKeyword(normalizedCategory, InstitutionalFacilityKeywords) ||
               ContainsAnyKeyword(normalizedGroupCategory, InstitutionalFacilityKeywords) ||
               ContainsAnyKeyword(normalizedCategory, CommercialKeywords) ||
               ContainsAnyKeyword(normalizedGroupCategory, CommercialKeywords);
    }

    bool LooksLikeAnchorEligibleBuilding(KakaoDocument document)
    {
        if (document == null)
        {
            return false;
        }

        string normalizedPlaceName = NormalizeText(document.place_name);
        string normalizedCategory = NormalizeText(document.category_name);
        string normalizedGroupCategory = NormalizeText(document.category_group_name);

        if (ContainsAnyKeyword(normalizedPlaceName, NonBuildingRepresentativeKeywords) ||
            ContainsAnyKeyword(normalizedCategory, NonBuildingRepresentativeKeywords) ||
            ContainsAnyKeyword(normalizedGroupCategory, NonBuildingRepresentativeKeywords))
        {
            return false;
        }

        if (ContainsAnyKeyword(normalizedCategory, CommercialKeywords) ||
            ContainsAnyKeyword(normalizedGroupCategory, CommercialKeywords))
        {
            return false;
        }

        return true;
    }

    string NormalizeRepresentativeName(string placeName)
    {
        string normalized = NormalizeText(placeName);
        foreach (string prefixToken in InstitutionalPrefixTokens)
        {
            normalized = normalized.Replace(NormalizeText(prefixToken), string.Empty);
        }

        return normalized;
    }

    ClusterGroupingType GetClusterGroupingType(KakaoDocument document)
    {
        string normalizedPlaceName = NormalizeText(document?.place_name);
        string normalizedCategory = NormalizeText(document?.category_group_name);

        if (ContainsAnyKeyword(normalizedPlaceName, CommercialKeywords) || ContainsAnyKeyword(normalizedCategory, CommercialKeywords))
        {
            return ClusterGroupingType.Commercial;
        }

        if (ContainsAnyKeyword(normalizedPlaceName, InstitutionalKeywords) || ContainsAnyKeyword(normalizedCategory, InstitutionalKeywords))
        {
            return ClusterGroupingType.Institutional;
        }

        return ClusterGroupingType.Default;
    }

    bool ContainsAnyKeyword(string normalizedValue, string[] keywords)
    {
        if (string.IsNullOrWhiteSpace(normalizedValue))
        {
            return false;
        }

        foreach (string keyword in keywords)
        {
            if (normalizedValue.Contains(NormalizeText(keyword)))
            {
                return true;
            }
        }

        return false;
    }

    string GetInstitutionalBuildingToken(KakaoDocument document)
    {
        string addressToken = ExtractInstitutionalBuildingToken(GetBestAddress(document));
        if (!string.IsNullOrWhiteSpace(addressToken))
        {
            return addressToken;
        }

        return ExtractInstitutionalBuildingToken(document?.place_name);
    }

    string ExtractInstitutionalBuildingToken(string sourceText)
    {
        if (string.IsNullOrWhiteSpace(sourceText))
        {
            return string.Empty;
        }

        string[] tokens = sourceText
            .Replace("(", " ")
            .Replace(")", " ")
            .Replace(",", " ")
            .Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);

        foreach (string token in tokens)
        {
            if (IsInstitutionalBuildingToken(token))
            {
                return token.Trim();
            }
        }

        return string.Empty;
    }

    bool IsInstitutionalBuildingToken(string token)
    {
        string normalizedToken = NormalizeText(token);
        if (string.IsNullOrWhiteSpace(normalizedToken))
        {
            return false;
        }

        if (ContainsAnyKeyword(normalizedToken, CommercialKeywords))
        {
            return false;
        }

        foreach (string suffix in InstitutionalBuildingSuffixes)
        {
            if (normalizedToken.EndsWith(NormalizeText(suffix)))
            {
                return true;
            }
        }

        return false;
    }
}
