using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.Networking;

public partial class GeospatialManager
{
    private class SearchDiagnostics
    {
        public int commercialRequestCount;
        public int campusRequestCount;
        public int keywordRequestCount;
        public int commercialResultCount;
        public int campusResultCount;
        public int keywordResultCount;
        public int mergedUniqueCount;
    }

    IEnumerator FetchAndClusterNearbyPlaces(double lat, double lon)
    {
        ResetAnchorDebugOverlay();
        Dictionary<string, KakaoDocument> mergedPlaces = new Dictionary<string, KakaoDocument>();
        SearchDiagnostics diagnostics = new SearchDiagnostics();
        int successCount = 0;

        if (useCommercialCategorySearch)
        {
            foreach (string categoryCode in GetCommercialCategoryCodes())
            {
                bool categorySucceeded = false;
                diagnostics.commercialRequestCount++;
                yield return StartCoroutine(FetchNearbyPlacesFromKakaoCategory(lat, lon, categoryCode, "commercial", 100, (requestSucceeded, fetchedDocuments) =>
                {
                    categorySucceeded = requestSucceeded;
                    diagnostics.commercialResultCount += fetchedDocuments.Count;
                    MergeFetchedPlaces(mergedPlaces, fetchedDocuments);
                }));

                if (categorySucceeded)
                {
                    successCount++;
                }
            }
        }

        if (useCampusCategorySearch)
        {
            foreach (string categoryCode in GetCampusCategoryCodes())
            {
                bool categorySucceeded = false;
                diagnostics.campusRequestCount++;
                yield return StartCoroutine(FetchNearbyPlacesFromKakaoCategory(lat, lon, categoryCode, "campus", 200, (requestSucceeded, fetchedDocuments) =>
                {
                    categorySucceeded = requestSucceeded;
                    diagnostics.campusResultCount += fetchedDocuments.Count;
                    MergeFetchedPlaces(mergedPlaces, fetchedDocuments);
                }));

                if (categorySucceeded)
                {
                    successCount++;
                }
            }
        }

        if (useKeywordSearch)
        {
            foreach (string keywordQuery in GetKeywordQueries())
            {
                bool keywordSucceeded = false;
                diagnostics.keywordRequestCount++;
                yield return StartCoroutine(FetchNearbyPlacesFromKakaoKeyword(lat, lon, keywordQuery, 300, (requestSucceeded, fetchedDocuments) =>
                {
                    keywordSucceeded = requestSucceeded;
                    diagnostics.keywordResultCount += fetchedDocuments.Count;
                    MergeFetchedPlaces(mergedPlaces, fetchedDocuments);
                }));

                if (keywordSucceeded)
                {
                    successCount++;
                }
            }
        }

        if (successCount == 0)
        {
            Debug.LogError("All Kakao place requests failed.");
            arUIManager?.ShowToast("주변 장소를 불러오지 못했습니다.");
            ClearAllContent();
            yield break;
        }

        List<KakaoDocument> allFetchedPlaces = mergedPlaces.Values.ToList();
        diagnostics.mergedUniqueCount = allFetchedPlaces.Count;
        LogSearchDiagnostics(diagnostics, allFetchedPlaces);
        ClusterAndBuildList(allFetchedPlaces);

        if (_autoGeneratedBuildingList.Count == 0)
        {
            Debug.LogWarning("No nearby places were found for the current location.");
            arUIManager?.ShowToast("주변 장소 정보가 없습니다.");
        }

        yield return StartCoroutine(CreateAllBuildingAnchors());
    }

    IEnumerator FetchNearbyPlacesFromKakaoCategory(double lat, double lon, string categoryCode, string sourceLabel, int sourcePriority, Action<bool, List<KakaoDocument>> onCompleted)
    {
        List<KakaoDocument> fetchedDocuments = new List<KakaoDocument>();
        bool requestSucceeded = false;

        for (int page = 1; page <= maxSearchPages; page++)
        {
            string url = $"https://dapi.kakao.com/v2/local/search/category.json?category_group_code={categoryCode}&x={lon}&y={lat}&radius={searchRadius}&page={page}";
            using (UnityWebRequest webRequest = UnityWebRequest.Get(url))
            {
                webRequest.SetRequestHeader("Authorization", "KakaoAK " + kakaoRestApiKey);
                yield return webRequest.SendWebRequest();

                if (webRequest.result == UnityWebRequest.Result.Success)
                {
                    requestSucceeded = true;
                    KakaoResponse response = JsonUtility.FromJson<KakaoResponse>(webRequest.downloadHandler.text);
                    if (response?.documents == null || response.documents.Length == 0) break;
                    foreach (KakaoDocument doc in response.documents)
                    {
                        PrepareFetchedDocument(doc, sourceLabel, categoryCode, sourcePriority);
                        fetchedDocuments.Add(doc);
                    }
                    if (response.meta == null || response.meta.is_end) break;
                }
                else
                {
                    Debug.LogWarning($"Kakao category request failed for {categoryCode}, page {page}: {webRequest.error}");
                    break;
                }
            }
        }

        onCompleted?.Invoke(requestSucceeded, fetchedDocuments);
    }

    IEnumerator FetchNearbyPlacesFromKakaoKeyword(double lat, double lon, string query, int sourcePriority, Action<bool, List<KakaoDocument>> onCompleted)
    {
        List<KakaoDocument> fetchedDocuments = new List<KakaoDocument>();
        bool requestSucceeded = false;

        for (int page = 1; page <= maxSearchPages; page++)
        {
            string escapedQuery = UnityWebRequest.EscapeURL(query);
            string url = $"https://dapi.kakao.com/v2/local/search/keyword.json?query={escapedQuery}&x={lon}&y={lat}&radius={searchRadius}&page={page}";
            using (UnityWebRequest webRequest = UnityWebRequest.Get(url))
            {
                webRequest.SetRequestHeader("Authorization", "KakaoAK " + kakaoRestApiKey);
                yield return webRequest.SendWebRequest();

                if (webRequest.result == UnityWebRequest.Result.Success)
                {
                    requestSucceeded = true;
                    KakaoResponse response = JsonUtility.FromJson<KakaoResponse>(webRequest.downloadHandler.text);
                    if (response?.documents == null || response.documents.Length == 0) break;
                    foreach (KakaoDocument doc in response.documents)
                    {
                        PrepareFetchedDocument(doc, "keyword", query, sourcePriority);
                        fetchedDocuments.Add(doc);
                    }
                    if (response.meta == null || response.meta.is_end) break;
                }
                else
                {
                    Debug.LogWarning($"Kakao keyword request failed for '{query}', page {page}: {webRequest.error}");
                    break;
                }
            }
        }

        onCompleted?.Invoke(requestSucceeded, fetchedDocuments);
    }

    IEnumerable<string> GetCommercialCategoryCodes()
    {
        return categoryCodes
            .Where(code => !string.IsNullOrWhiteSpace(code))
            .Select(code => code.Trim().ToUpperInvariant())
            .Distinct();
    }

    IEnumerable<string> GetCampusCategoryCodes()
    {
        return campusCategoryCodes
            .Where(code => !string.IsNullOrWhiteSpace(code))
            .Select(code => code.Trim().ToUpperInvariant())
            .Except(GetCommercialCategoryCodes())
            .Distinct();
    }

    IEnumerable<string> GetKeywordQueries()
    {
        return keywordQueries
            .Where(query => !string.IsNullOrWhiteSpace(query))
            .Select(query => query.Trim())
            .Distinct();
    }

    void PrepareFetchedDocument(KakaoDocument document, string searchSource, string sourceQuery, int sourcePriority)
    {
        if (document == null)
        {
            return;
        }

        document.search_source = searchSource;
        document.source_query = sourceQuery;
        document.source_priority = sourcePriority;

        if (string.IsNullOrWhiteSpace(document.category_group_name) && searchSource == "keyword")
        {
            document.category_group_name = "키워드 검색";
        }
    }

    void MergeFetchedPlaces(Dictionary<string, KakaoDocument> mergedPlaces, List<KakaoDocument> fetchedDocuments)
    {
        foreach (KakaoDocument document in fetchedDocuments)
        {
            string dedupeKey = GetDocumentDedupeKey(document);
            if (mergedPlaces.TryGetValue(dedupeKey, out KakaoDocument existingDocument))
            {
                if (ShouldReplaceDocument(existingDocument, document))
                {
                    mergedPlaces[dedupeKey] = document;
                }
                continue;
            }

            mergedPlaces[dedupeKey] = document;
        }
    }

    bool ShouldReplaceDocument(KakaoDocument existingDocument, KakaoDocument candidateDocument)
    {
        int existingScore = GetDocumentQualityScore(existingDocument);
        int candidateScore = GetDocumentQualityScore(candidateDocument);
        return candidateScore > existingScore;
    }

    int GetDocumentQualityScore(KakaoDocument document)
    {
        int score = document?.source_priority ?? 0;
        if (!string.IsNullOrWhiteSpace(document?.road_address_name)) score += 20;
        if (!string.IsNullOrWhiteSpace(document?.phone)) score += 5;
        if (!string.IsNullOrWhiteSpace(document?.category_group_name) && document.category_group_name != "키워드 검색") score += 10;
        return score;
    }

    string GetDocumentDedupeKey(KakaoDocument document)
    {
        string normalizedName = NormalizeText(document?.place_name);
        string normalizedAddress = NormalizeText(GetBestAddress(document));
        string normalizedCoords = $"{NormalizeCoordinate(document?.y)}|{NormalizeCoordinate(document?.x)}";

        if (!string.IsNullOrWhiteSpace(normalizedAddress))
        {
            return $"{normalizedName}|{normalizedAddress}";
        }

        return $"{normalizedName}|{normalizedCoords}";
    }

    string GetBestAddress(KakaoDocument document)
    {
        if (!string.IsNullOrWhiteSpace(document?.road_address_name))
        {
            return document.road_address_name;
        }

        return document?.address_name ?? string.Empty;
    }

    string NormalizeText(string value)
    {
        return string.IsNullOrWhiteSpace(value)
            ? string.Empty
            : value.Trim().Replace(" ", string.Empty).ToLowerInvariant();
    }

    string NormalizeCoordinate(string value)
    {
        if (!double.TryParse(value, out double parsed))
        {
            return "0";
        }

        return Math.Round(parsed, 5).ToString("F5");
    }

    void LogSearchDiagnostics(SearchDiagnostics diagnostics, List<KakaoDocument> mergedPlaces)
    {
        if (!logSearchDiagnostics)
        {
            return;
        }

        int injeHits = mergedPlaces.Count(doc => !string.IsNullOrWhiteSpace(doc.place_name) && doc.place_name.Contains("인제대"));
        int dormitoryHits = mergedPlaces.Count(doc => !string.IsNullOrWhiteSpace(doc.place_name) && (doc.place_name.Contains("기숙사") || doc.place_name.Contains("원룸")));
        int nightlifeHits = mergedPlaces.Count(doc => !string.IsNullOrWhiteSpace(doc.place_name) && (doc.place_name.Contains("술") || doc.place_name.Contains("주점") || doc.place_name.Contains("포차")));

        Debug.Log(
            $"[SearchDiagnostics] commercial requests/results: {diagnostics.commercialRequestCount}/{diagnostics.commercialResultCount}, " +
            $"campus requests/results: {diagnostics.campusRequestCount}/{diagnostics.campusResultCount}, " +
            $"keyword requests/results: {diagnostics.keywordRequestCount}/{diagnostics.keywordResultCount}, " +
            $"merged unique: {diagnostics.mergedUniqueCount}, " +
            $"inje hits: {injeHits}, dormitory or room hits: {dormitoryHits}, nightlife hits: {nightlifeHits}");
    }
}
